import numpy as np
from sympy import *
import math


MAX_STEP = 10



class JacobianController:
    def __init__(self, arm):
        # the controller should save a reference to the arm it's controlling
        self.arm = arm

    def control(self, target):
        if self.arm.get_num_joints() == 2:
            # if arm has 2 joints            
            self.control2J2D(target)
        elif self.arm.get_num_joints() == 3:
            # if arm has 3 joints
            self.control3J2D(target)
        elif self.arm.get_num_joints() == 6:
            # if arm has 6 joints
            self.control6J2D(target)
        else:
            raise Exception("JacobianController.control(target): Can't control an arm with this amount joints.")

    def control2J2D(self, target):
        
        pass

    def control3J2D(self, target):

        pass

    def control6J2D(self, target):
        curr_end = self.arm.endeffector()
        delta_pos = target - curr_end
        # we limit the size of the delta_pos vector as MAX_STEP
        # to avoid making large steps
        if delta_pos.r > MAX_STEP:
            delta_pos.r = MAX_STEP

        t0 = self.arm.thetas[0]
        t1 = self.arm.thetas[1]
        t2 = self.arm.thetas[2]
        t3 = self.arm.thetas[3]
        t4 = self.arm.thetas[4]
        t5 = self.arm.thetas[5]

        l0 = self.arm.lengths[0]
        l1 = self.arm.lengths[1]
        l2 = self.arm.lengths[2]
        l3 = self.arm.lengths[3]
        l4 = self.arm.lengths[4]
        l5 = self.arm.lengths[5]

        a_0_0 = ( 100*( (-( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + 100*(( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + (( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4))*np.cos(t5) + ( 100*( (-( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) + 100*(-( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - (( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4))*np.sin(t5) + ( 100*(-( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + 100*( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + (100*( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + 100*(( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4) + ( 100*( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + (100*( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + 100*( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3) + ( 100*np.sin(t0)*np.sin(t1) - 100*np.cos(t0)*np.cos(t1))*np.sin(t2) + (-100*np.sin(t0)*np.cos(t1) - 100*np.sin(t1)*np.cos(t0))*np.cos(t2) - 100*np.sin(t0)*np.cos(t1) - 100*np.sin(t0) - 100*np.sin(t1)*np.cos(t0)
        a_0_1 = ( 100*( (-( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + 100*(( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + (( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4))*np.cos(t5) + ( 100*( (-( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) + 100*(-( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - (( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4))*np.sin(t5) + ( 100*(-( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + 100*( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + (100*( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + 100*(( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4) + ( 100*( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + (100*( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) + 100*( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3) + ( 100*np.sin(t0)*np.sin(t1) - 100*np.cos(t0)*np.cos(t1))*np.sin(t2) + (-100*np.sin(t0)*np.cos(t1) - 100*np.sin(t1)*np.cos(t0))*np.cos(t2) - 100*np.sin(t0)*np.cos(t1) - 100*np.sin(t1)*np.cos(t0) 
        a_0_2 = ( 100*(-(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - ( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4) + 100*(( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + (( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4))*np.sin(t5) + ( 100*( (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + ( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4) + 100*( ( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + (( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4))*np.cos(t5) + ( 100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + 100*( ( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4) + (100*( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + 100*(( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + (-100*(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + (100*( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.cos(t2) - 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3) - (-100*np.sin(t0)*np.sin(t1) + 100*np.cos(t0)*np.cos(t1))*np.sin(t2) + (-100*np.sin(t0)*np.cos(t1) - 100*np.sin(t1)*np.cos(t0))*np.cos(t2)
        a_0_3 = ( 100*(-(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + 100*((-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4))*np.cos(t5) + ( 100*(-(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) + 100*(-(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4))*np.sin(t5) + (-100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + 100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + (100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - 100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4) + (-100*(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - (100*(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3)
        a_0_4 = ( 100*(-(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) - ( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) - 100*((-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4))*np.sin(t5) + (-100*( (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + 100*( (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4))*np.cos(t5) - ( 100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + 100*( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + (100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - 100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4)
        a_0_5 = ( 100*(-(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) - ( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) - 100*((-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4))*np.sin(t5) + (-100*( (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + 100*( (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4))*np.cos(t5) - ( 100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + 100*( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*sin(t2))*cos(t3))*sin(t4) + (100*(-(-sin(t0)*sin(t1) + cos(t0)*cos(t1))*sin(t2) + (-sin(t0)*cos(t1) - sin(t1)*cos(t0))*cos(t2))*cos(t3) - 100*((-sin(t0)*sin(t1) + cos(t0)*cos(t1))*cos(t2) + (-sin(t0)*cos(t1) - sin(t1)*cos(t0))*sin(t2))*np.sin(t3))*np.cos(t4)
        
        a_1_0 = ( 100*( (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3) + (( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3))*np.sin(t4) + 100*(((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3) + ((np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3))*np.cos(t4))*np.cos(t5) + (100*((-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3) + ((np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3))*np.cos(t4) + 100*(-((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3) - ((np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3))*np.sin(t4))*np.sin(t5) + (100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3) + 100*((np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3))*np.sin(t4) + (100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3) + 100*((np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3))*np.cos(t4) + (100*(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3) + (100*(np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + (-100*np.sin(t0)*np.sin(t1) + 100*np.cos(t0)*np.cos(t1))*np.cos(t2) + (-100*np.sin(t0)*np.cos(t1) - 100*np.sin(t1)*np.cos(t0))*np.sin(t2) - 100*np.sin(t0)*np.sin(t1) + 100*np.cos(t0)*np.cos(t1) + 100*np.cos(t0)
        a_1_1 = ( 100*( (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3) + (( np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3))*np.sin(t4) + 100*(((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3) + ((np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3))*np.cos(t4))*np.cos(t5) + (100*((-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3) + ((np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3))*np.cos(t4) + 100*(-((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3) - ((np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3))*np.sin(t4))*np.sin(t5) + (100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3) + 100*((np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3))*np.sin(t4) + (100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3) + 100*((np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3))*np.cos(t4) + (100*(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3) + (100*(np.sin(t0)*np.sin(t1) - np.cos(t0)*np.cos(t1))*np.sin(t2) + 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + (-100*np.sin(t0)*np.sin(t1) + 100*np.cos(t0)*np.cos(t1))*np.cos(t2) + (-100*np.sin(t0)*np.cos(t1) - 100*np.sin(t1)*np.cos(t0))*np.sin(t2) - 100*np.sin(t0)*np.sin(t1) + 100*np.cos(t0)*np.cos(t1)
        a_1_2 = ( 100*(-(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) - ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + 100*((-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4))*np.sin(t5) + (100*((-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) + 100*((-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4))*np.cos(t5) + (100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + 100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) + (100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + 100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4) + (-100*(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + 100*(-np.sin(t0)*np.cos(t1) - np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + (100*(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - 100*(np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3) + (-100*np.sin(t0)*np.sin(t1) + 100*np.cos(t0)*np.cos(t1))*np.cos(t2) - (100*np.sin(t0)*np.cos(t1) + 100*np.sin(t1)*np.cos(t0))*np.sin(t2)
        a_1_3 = ( 100*( (-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) - ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4) + 100*(-((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4))*np.cos(t5) + (100*((-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4) + 100*(((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) - ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4))*np.sin(t5) + (100*(-(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - 100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4) + (-100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + 100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) - (100*(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + 100*(np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + (100*(-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - 100*(np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3)
        a_1_4 = (-100*(-( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + 100*(-((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) - ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4))*np.sin(t5) + (100*(-((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) - 100*(((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4))*np.cos(t5) + (-100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + 100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) - (100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + 100*((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4)
        a_1_5 =-( 100*(-( (-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - ( np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.sin(t4) + 100*(((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.cos(t4))*np.sin(t5) + (100*(-((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.sin(t3) + ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.cos(t3))*np.cos(t4) - 100*(((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.sin(t2) + (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.cos(t2))*np.cos(t3) + ((-np.sin(t0)*np.sin(t1) + np.cos(t0)*np.cos(t1))*np.cos(t2) - (np.sin(t0)*np.cos(t1) + np.sin(t1)*np.cos(t0))*np.sin(t2))*np.sin(t3))*np.sin(t4))*np.cos(t5)

    
        J = np.array([[a_0_0, a_0_1, a_0_2, a_0_3, a_0_4, a_0_5], [a_1_0, a_1_1, a_1_2, a_1_3, a_1_4, a_1_5]])

        iJ = np.linalg.pinv(J)

        # the dot product between iJ and the desired displacement
        # in the end-effector gives us the change necessary in joint values
        delta_joints = iJ.dot(np.array([delta_pos.x, delta_pos.y]))

        # with delta_joints in hand, we move the arm
        self.arm.move( delta_joints )
                


        pass
    